### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by loadbrain** [jammeryhq/gridsome-starter-articles#3]
Hi,

I play around with this template to learn more.
Now I installed Splide, https://splidejs.com/, a Vue Slider.
With `gridsome develop` everything is ok.
If I run `gridsome build` I get this error:
`...
Execute GraphQL (43 queries) - 1.28s  
Could not generate HTML for "/resources/filter/tag/gridsome":  
ReferenceError: self is not defined
    at Object.SjWa (node_modules/@splidejs/splide/dist/js/splide.esm.js:16:1)
`
Can you help me what I can do?
What is the problem?

**Comment by noxify** [comment]
Hi,

which Splide package are you using?

* Splide Vue: https://github.com/Splidejs/vue-splide
* Splide: https://github.com/Splidejs/splide

I have seen this issue https://github.com/Splidejs/vue-splide/issues/15 and it seems there is currently no SSR support.

You could try to load the library via https://gridsome.org/docs/assets-scripts/#without-ssr-support

**Comment by loadbrain** [comment]
Hi, 

thanks, I used the second one.
Ok, as I am new in this things I first have to figure out what SSR really means.. 😉
But thanks for the hint in gridsome, I will check this out.

**Comment by noxify** [comment]
maybe this helps to understand was SSR is: https://www.youtube.com/watch?v=GQzn7XRdzxY

**Comment by loadbrain** [comment]
Hi,
worked for me with  https://gridsome.org/docs/assets-scripts/#without-ssr-support :+1: 
Slider.vue is one file imported in Header.vue and there:
`<ClientOnly>
<Slider />
</ClientOnly>`

This works without getting
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__esModule' of undefined`
